export const categories = [
  "All",
  "Main Gates",
  "Safety Grills",
  "Railings",
  "Sheds",
  "Doors",
  "Furniture Frames",
  "Industrial",
  "Custom Fabrication",
];

export const products = [
  {
    id: 1,
    name: "Steel Main Gate",
    category: "Main Gates",
    badge: "Residential",
    description: "Strong and durable steel gate designed for homes and commercial entrances.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: true,
  },
  {
    id: 2,
    name: "Designer Main Gate",
    category: "Main Gates",
    badge: "Premium",
    description: "Modern laser-cut design wala premium gate jo property ki shaan badhaaye.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    featured: true,
  },
  {
    id: 3,
    name: "Double Door Entrance Gate",
    category: "Main Gates",
    badge: "Commercial",
    description: "Large property aur farmhouse entrance ke liye wide double door gate.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
    featured: false,
  },
  {
    id: 4,
    name: "Sliding Gate",
    category: "Main Gates",
    badge: "Space Saving",
    description: "Space-saving sliding mechanism ke saath modern entrance solution.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80",
    featured: false,
  },
  {
    id: 5,
    name: "Window Safety Grill",
    category: "Safety Grills",
    badge: "Residential",
    description: "Home security ke liye strong aur durable window grill.",
    image: "https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?w=600&q=80",
    featured: true,
  },
  {
    id: 6,
    name: "Balcony Safety Grill",
    category: "Safety Grills",
    badge: "Safety",
    description: "Balcony protection aur safety ke liye fabricated grill.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
    featured: false,
  },
  {
    id: 7,
    name: "Decorative Grill Design",
    category: "Safety Grills",
    badge: "Designer",
    description: "Security ke saath attractive appearance — home decor aur safety dono.",
    image: "https://images.unsplash.com/photo-1558618047-f4e60cde054f?w=600&q=80",
    featured: false,
  },
  {
    id: 8,
    name: "Shop Security Grill",
    category: "Safety Grills",
    badge: "Commercial",
    description: "Shops aur commercial properties ki security ke liye heavy-duty grill.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    featured: false,
  },
  {
    id: 9,
    name: "Staircase Railing",
    category: "Railings",
    badge: "Indoor/Outdoor",
    description: "Indoor aur outdoor staircase ke liye strong aur stylish railing.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    featured: false,
  },
  {
    id: 10,
    name: "Balcony Railing",
    category: "Railings",
    badge: "Modern",
    description: "Modern aur durable railing system for balconies.",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=80",
    featured: true,
  },
  {
    id: 11,
    name: "Terrace Railing",
    category: "Railings",
    badge: "Safety",
    description: "Terrace safety ke liye professionally fabricated railing work.",
    image: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=600&q=80",
    featured: false,
  },
  {
    id: 12,
    name: "Stainless Steel Railing",
    category: "Railings",
    badge: "Premium",
    description: "Premium finish aur rust resistance ke saath stainless steel railing.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80",
    featured: false,
  },
  {
    id: 13,
    name: "Parking Shed",
    category: "Sheds",
    badge: "Residential",
    description: "Car aur bike parking ke liye weather-proof shed structure.",
    image: "https://images.unsplash.com/photo-1558980394-4c7c9299fe96?w=600&q=80",
    featured: true,
  },
  {
    id: 14,
    name: "Industrial Shed Structure",
    category: "Sheds",
    badge: "Industrial",
    description: "Factory aur warehouse use ke liye heavy-duty shed fabrication.",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    featured: false,
  },
  {
    id: 15,
    name: "Tin Shed Fabrication",
    category: "Sheds",
    badge: "Affordable",
    description: "Residential aur commercial properties ke liye tin shed solution.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    featured: false,
  },
  {
    id: 16,
    name: "Entrance Canopy Shed",
    category: "Sheds",
    badge: "Decorative",
    description: "Home aur shop entrance covering ke liye stylish canopy shed.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    featured: false,
  },
  {
    id: 17,
    name: "Steel Security Door",
    category: "Doors",
    badge: "Security",
    description: "Strong security purpose door jo intruder resistance provide kare.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    featured: false,
  },
  {
    id: 18,
    name: "Metal Frame Door",
    category: "Doors",
    badge: "Custom Size",
    description: "Custom size fabrication ke saath metal frame door.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
    featured: false,
  },
  {
    id: 19,
    name: "Commercial Entry Door",
    category: "Doors",
    badge: "Commercial",
    description: "Office aur shop entrance ke liye durable commercial door.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    featured: false,
  },
  {
    id: 20,
    name: "Iron Bed Frame",
    category: "Furniture Frames",
    badge: "Home Use",
    description: "Custom size metal bed frame jo durable aur stylish ho.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    featured: false,
  },
  {
    id: 21,
    name: "Metal Table Frame",
    category: "Furniture Frames",
    badge: "Home/Office",
    description: "Home aur office use ke liye strong metal table frame.",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80",
    featured: false,
  },
  {
    id: 22,
    name: "Storage Rack",
    category: "Furniture Frames",
    badge: "Utility",
    description: "Shop aur warehouse ke liye heavy-duty storage rack solution.",
    image: "https://images.unsplash.com/photo-1558618047-f4e60cde054f?w=600&q=80",
    featured: true,
  },
  {
    id: 23,
    name: "Industrial Support Structure",
    category: "Industrial",
    badge: "Industrial",
    description: "Machine support aur heavy industrial fabrication work.",
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80",
    featured: false,
  },
  {
    id: 24,
    name: "Heavy Duty Fabrication Frame",
    category: "Industrial",
    badge: "Heavy Duty",
    description: "Industrial application ke liye precision fabricated heavy frame.",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
    featured: false,
  },
];

export const featuredProducts = products.filter((p) => p.featured);
